 function MainEngine() {       
     this._lexicon;
     this._all_hebrew_words_lexicon;
     this._localStorageEngine;
               
     this.init = function(fctDone1,fctDone2) {          
            window.myEngine._localStorageEngine = new LexiconLocalStorage();
            window.myEngine._localStorageEngine.getLexicon(function(lexicon) {                
                var new_lexicon = new Lexicon(window.myEngine._localStorageEngine._my_lexicon_id);
                                
                new_lexicon.initFromLexicon(lexicon);                
                window.myEngine._lexicon = new_lexicon;
                                                                                                                                                              
/*var default_words = [["manifester","להפגין",""],
["en attendant","ביינתים",""],
["j'en ai marre","נמאס לי",""],
["immédiatement","מייד",""],
["je suis en colère","אני כועס",""],
["tasse","כוס",""],
["jaloux","קנאי",""],
["compétition","תחרות",""],
["manifestation","הפגנה",""],
["tu me manques","אני מתגעגע לך",""],
["cuisine","מטבח",""],
["rouge","אדום",""],
["simplement","פשוט",""],
["couverts/outils","כלים",""],
["dense/surpeuplé","צפוף",""],
["couleur","צבע",""],
["couleurs","צבעים",""],
["aider à","לעזור ל...",""],
["il n'a pas le choix","אין לו בריחה",""],
["en forme","בכושר",""],
["réussir","להצליח",""],
["il y a longtemps","מזמן","mizman"],
["tromper/trahir","לבגוד","livgod"],
["épisode/chapitre","פרק","pereq"],
["se rencontrer","להפגש עם","léhipaguesh im"],
["message","הודעה","odaa"],
["terminer","לסיים",""],
["se séparer","להפרד","léhipared"],
["chanteur","זמר","zamar"],
["il la drague","הוא מתחיל איתה",""],
["elle est folle de lui","היא משוגעת עליו",""],
["surpris/étonné","מופתע","moufta"],
["abricot","משמש","michmech"],
["fini","נגמר",""],
["célèbre","מפורסם",""],
["poivron","פלפל",""],
["vraiment","ממש",""],
["désert","מדבר",""],
["peau","עור",""],
["astuce/truc","הקונץ",""],
["invité","אורח","orêakh"],
["distance","מרחק",""],
["profession","מקצוע","miktsoa"],
["médecin","רופא",""],
["lumière","אור",""],
["train","רכבת",""],
["choisir","לבחר","livkhor"],
["louer (de)","לשכור","liskore"],
["vérifier","לבדוק","livdoke"],
["mesurer","למדוד","limdode"],
["partenaire","שותף","choutafe"],
["vendre","למכור","limkore"],
["finir","לגמור","ligmore"],
["les employés","העובדים",""],
["ouvrir","לפתוח","liftoakh"],
["se réjouir","לשמוח","lismoakh"],
["envoyer/poster","לשלוח ל...","lichloakh"],
["oublier","לשכוח","lichcoakh"],
["entretien d'embauche","ראיון עבודה","réayone avoda"],
["déterminer/fixer","לקבוע","likboa"],
["candidat","מועמד","mou'amade"],
["nager","לשחות","lisrote"],
["piscine","בריכה","brékha"],
["signer","לחתום על","laratome"],
["partie (négociations)","צד","tsade"],
["parties (négociations)","צדדים",""],
["accord","הסכם","héskême"],
["ministre","שר","sare"],
["défense","ביטחון",""],
["arrêter (cesser)","לעצור","la'atsôre"],
["passage piétons","מעבר החצייה",""],
["croire","להאמין","léha'amîne"],
["dégoûter","להגעיל את","léhag'île"],
["être dégoûté","להיגעל מ","léhiga'êle mi"],
["âne","חמור","ramôre"],
["tourner/s'adresser/donner sur","לפנות","lifnote"],
["éducation","חינוך","rinour"],
["je me bat contre moi","אני נלחם בעצמי","ani nilrame betsmi"],
["salle de sport","מכון כושר","marone kocher"],
["concentration","ריכוז","ricouze"],
["rater","לפספס","lefasfess"],
["rire","לצחוק","litsroque"],
["se moquer de","לצחוק על","litsroque al"],
["enquête","תחקיר","tarkire"],
["évènement","אירוע","eyroua"],
["globe terrestre","כדור הארץ","cadour aarets"],
["rond","עגול","agole"],
["plat","שטוח","chatouare"],
["être d'accord","להסכים","léaskime"],
["président (PDG)","מנכל","mankale"],
["demander à","לבקש מ","levakesh mi"],
["lieux de divertissement","מקומות בילוי","mékomote bilouye"],
["passer du bon temps","לבלות","levalote"],
["se transformer","להשתנות","léhichtanote"],
["changer/modifier","לשנות","léchanote"],
["tu as raison","אתה צודק","ata tsodek"],
["personnage","דמות","dmoute"],
["différent","שונה","choné"],
["sérieux","רציני","rétsini"],
["honte","בושה","bousha"],
["comportement","התנהגות","hitnahagoute"],
["se comporter","להתנהג","léhitnaègue"],
["groupe (bande)","להקה","léhaka"],
["organiser","לארגן","léarguène"],
["étoile","כוכב","corave"],
["punition","עונש","onèche"],
["jeu","משחק","misrak"],
["diplôme","תעודה","téouda"],
["ça va pas, jamais de la vie !","מה פתאום","ma pitome"],
["équipe","צוות","tsévette"],
["tenir","להחזיק","léarzik"],
["trouver","למצוא","limtso"],
["fleur","פרח","pérar"],
["manger","לאכול","léérole"],
["loi","חוק","rok"],
["dis moi","תגיד לי","taguide li"],
["pleurer","לבכות","livcote"],
["bientôt","עוד מעט","ode méate"],
["il n'y a pas de quoi","אין בעד מה","eyn béad ma"],
["beaucoup","המון","amone"],
["avant","קודם","kodème"],
["plus tard","אחר כך","arar kar"],
["il faut/avoir besoin de","צריך","tsarir"],
["patience","סבלנות","savlanoute"],
["malgré/bien que","למרות","lamrote"],
["tempêtes de sable","סופות חול","sofot role"],
["brume","אובך","ovère"],
["farine","קמח","quémar"],
["oignon","בצל","batsal"],
["huile","שמן","chémène"],
["gras","שמן","chamène"],
["mince","רזה","razé"],
["graisse","שומן","choumane"],
["concombre","מלפפון","mélaféfone"],
["tomate","עגבניה","agvanya"],
["plante","צמח","tsémar"],
["cactus","צבר","tsabar"],
["menthe (mot arabe)","נענע","nana"],
["menthe","מנטה","mènta"],
["carotte","גזר","guézer"],
["ainsi","כך","car"],
["donation","נתינה","nétina"],
["volontaires/bénévoles","מתנדבים","mitnadvime"],
["une visite","ביקור","bikouve"],
["j'ai la grippe","אני מצונן","ani metsounane"],
["vieillir","להזדקן","léhizdaquène"],
["être photographié","להצטלם","léhitsatélem"],
["être appelé au téléphone","להתקשר","léhitkasher"],
["prendre froid","להצטנן","léhitstanène"],
["pauvre","עני","ani"],
["généreux/philanthrope","נדיב","nadiv"],
["générosité","נדיבות","ndivout"],
["minorité","מיעוט","miout"],
["journal intime","יומן","iomane"],
["cette année","השנה","achana"],
["adulte","מבוגר","mévougar"],
["ennuyeux","משעמם","méchaamem"],
["charge/fardeau","נטל","nétèl"],
["constitution","חוקה","rouka"],
["crashé (whatsapp a crashé)","קורס","korès"],
["condition/état","תנאי","ténayi"],
["conditions (de vie)","תנאים","ténayime"],
["pastèque","אבטיח","avatyar"],
["embrasser","לנשק","lénachèque"],
["aéroport","שדה התעופה","sédé atéoufa"],
["je me sépare","אני ניפרד","ani nifrade"],
["se cacher","להסתתר","léhistatère"],
["complexe/compliquée (fille)","מורכבת","mourkévéte"],
["balance","מאזנים","moznayime"],
["complexe (garçon)","מורכב","mourkâve"],
["complexité","מורכבות","mourkavoûte"],
["construire un logiciel","לבנות תוכנה","livnote torna"],
["période d'essai","תקופת נסיון","tékoufate nissayone"],
["prendre en photo","לצלם","létsalème"],
["photocopie","צילום","tsiloume"],
["promotion","קידום","quidoume"],
["gagner","להרוויח","léarviare"],
["être en colère","לכעוס","lirosse"],
["se coucher","לשכב","lichkâve"],
["courage","אומץ","ometsse"],
["courageux","אמיץ","amîtsse"],
["courageuse","אמיצה","amîtssa"],
["conduire","לנהוג","linogue"],
["s'inquiéter","לדאג ל...","lidogue"],
["inquiétude/souci","דאגה","déaga"],
["inquiéter/causer des soucis","להדאיג","léhadigue"],
["rester","להישאר","léhichaère"],
["différence","הבדל","évdèle"],
["possibilités d'évolution","אפשרויות קדום","efcharouiote quidoume"],
["entreprise","חברה","révra"],
["analyste (informatique)","מנתח","ménatéra"],
["culot","חוצפה","routspa"],
["charme","קסם","kêsséme"],
["poubelle/ordure","זבל","zével"],
["c'est un droit","זאת זכות","zot zroute"],
["j'ai le droit","זכותי","zrouti"],
["dessin animé","סרט מצויר","seret metsouyar"],
["c'est génial ! Top !","חבל על הזמן","raval al azmane"],
["lapin","שפן","chafane"],
["autruche","בת יענה","bat yahana"],
["autruches","בנות יענה","banote yahana"],
["bâton","מקל","maquel"],
["toucher","לגעת","lagaate"],
["attraper","לתפוס","litposse"],
["résoudre","לפתור","liftore"],
["tirer/retirer (de l'argent)","למשוך","limchore"],
["policier","שוטר","chotere"],
["réalité","מציאות","métsiyoute"],
["découvrir","לגלות","légalote"],
["par coeur","בעל פה","béal pé"],
["remarquer/faire attention","לשים לב","lasime lève"],
["gênant","לא נעים","lo naime"],
["stratégie","אסטרטגיה","astratégia"],
["action (part)","מניה","ménaya"],
["sifflement","שריקה","shrika"],
["allumer","להדליק","léhadlique"],
["habiller","להלביש","léhalbiche"],
["enregistrer","להקליט","léhaklite"],
["laisser","להשאיר","léhachire"],
["promettre","להבטיח","léhavtiare"],
["insérer","להכניס","léharnisse"],
["expliquer","להסביר","léhasbire"],
["contrat","חוזה","rozé"],
["électricité","חשמל","rachmale"],
["locataire","דייר","dayare"],
["pire","יותר גרוע","yoter garoua"],
["niveau","רמה","rama"],
["lorsque","כש...","qché..."],
["pour/dans le but","כדי","quédey"],
["suffire (réussir à temps)","להספיק","léaspik"],
["solution","פתרון","pitarone"],
["solutions","פתרונות","pitronote"],
["quel culot !","איזו חוצפה !","eizo routspa !"],
["direct","ישיר","yachir"],
["le moins pire","הרע במיעוטו","ara bimiyouto"],
["but/objectif","מטרה","matara"],
["juge (un)","שופט","chofète"],
["voter/pointer du doigt","להצביע","léatsbiya"],
["en général/habituellement","בדרך כלל","bédérere rlal"],
["droit","ישר","yachar"],
["vrai","אמיתי","amiti"],
["nord","צפון","tsafone"],
["sud","דרום","darome"],
["est (orientation)","מזרח","mizrare"],
["ouest","מערב","maarave"],
["date","תאריך","taarir"],
["agence juive","סוכנות היהודית","sournoute hyéoudite"],
["avantage","יתרון","yitarone"],
["promesse","הבטחה","havtara"],
["en bas","למטה","lémata"],
["haut","גבוה","gavôa"],
["se précipiter","למהר","lémaer"],
["annuler","לבטל","lévatel"],
["licencier","לפטר","léfatére"],
["raccrocher/rompre le lien","לנתק","lénatek"],
["cuisiner","לבשל","lévachel"],
["fumer","לעשן","léachen"],
["jouer (un instrument)","לנגן","lénaguène"],
["directeur","מנהל","ménahèle"],
["expérience (travail)","ניסיון","nissayone"],
["salaire","משכורת","mascorète"],
["recommandation","המלצה","hamlatsa"],
["emploi à mi-temps","חצי משרה","retsi misra"],
["emploi à temps plein","משרה מלאה","misra méléa"],
["formation (études)","השכלה","haskala"],
["langue (langage)","שפה","safa"],
["curriculum vitae","קורות חיים","quorote rayime"],
["ingénieur","מהנדס","méandès"],
["situation familiale","מצב משפחתי","matsave mishparti"],
["marié","נשוי","nassouille"],
["célibataire","רווק","ravak"],
["tu me prends pour qui ? (m)","מה אני נראה לך ?","ma ani nira lar"],
["tu me prends pour qui ? (f)","מה אני נראית לך ?","ma ani nirét lar"],
["code secret","קוד סודי","code sodi"],
["chiffre","ספרה","sifra"],
["faire une faveur/rendre service","לעשות טובה","laassote tova"],
["faveur/service","טובה","tova"],
["sécurité routière","פטיחות בדרכים","pétiroute badrarime"],
["force","כוח","coar"],
["publicité","פרסומת","pirsomète"],
["stage","קורס","course"],
["tiroir","מגרה","méguéra"],
["réchauffer","להתחמם","léhitramème"],
["refroidir","להתקרר","léhitquarère"],
["carosse","מרכבה","mercava"],
["muraille","חומה","roma"],
["site de rencontre","אתר הכרויות","atar érrouyote"],
["en même temps/simultanément","תוך כדי","tor quédey"],
["faire monter","להעלות","léaalote"],
["ascenceur","מעלית","maalite"],
["éclater (de rire)/ pénétrer (par effraction)","לפרוץ","lifrotse"],
["devant toi","לפניך","léfanira"],
["impatient","חסר סבלנות","rassar savlanoute"],
["du tout","בכלל","birlal"],
["manquant","חסר","rassère"],
["direction (sens)","כיוון","kivoune"],
["envers","כלפי","clapi"],
["envers moi","כלפיי","clapye"],
["circonstances","נסיבות","nésibote"],
["dérangement","הפרעה","afra'a"],
["déranger","להפריע","léhafri'a"],
["apporter/emmener","להביא","léhabia"],
["se tenir debout","לעמוד","laamode"],
["avis","דעה","déa"],
["à mon avis","לדעתי","lédaati"],
["écouter","להקשיב","léakchive"],
["larmes","דמעות","dimaote"],
["peu à peu/petit à petit","בהדרגה","béhadraga"],
["remettre (un message)","למסור","limsore"],
["requête/tournant","פניה","pniya"],
["bureau (administration)","לשכה","lichka"],
["bureau de l'emploi","לשכת התעסוקה","lichkat ataasouqua"],
["effraction","פריצה","pritsa"],
["art","אומנות","omanoute"],
["alors","אז","az"],
["frère","אח","ar"],
["en arrière","אחורה","arora"],
["soeur","אחות","arote"],
["soeurs","אחיות","arayote"],
["neveu","אחיין","aryane"],
["nièce","אחיינית","aryanite"],
["autre","אחר","arère"],
["dernier","אחרון","ararone"],
["nourriture","אוכל","orèle"],
["oreille","אוזן","ozène"],
["ambiance/atmosphère","אווירה","avira"],
["amour","אהבה","ahava"],
["légende","אגדה","agada"],
["air","אוויר","avir"],
["vérité","אמת","émète"],
["au-dessus","מעל","méal"],
["réfrigérateur","מקרר","makrère"],
["police","משטרה","michtara"],
["enfin","סוף סוף","sof sof"],
["interdit","אסור","asour"],
["nez","אף","af"],
["personne","אף אחד","af érade"],
["même","אפילו","afilou"],
["doigt","אצבע","étsba"],
["long","ארוך","arore"],
["feu","אש","èche"],
["gris","אפור","afore"],
["correspondre (par letttes)","להתכתב","léhitkatève"],
["peut-être","אולי","oulaye"],
["armoire","ארון","arone"],
["après-midi","אחרי הצהריים","araraye atsaarayime"],
["quel","איזה","eyzé"],
["comment","איך","èrre"],
["il n'y a pas","אין","eyne"],
["quelle","איזו","eyzo"],
["vers, à...","אל","èle"],
["quels (quelles)","אילו","eylou"],
["ce sont","אלה","élé"],
["(ne...) mais...","אלא","éla"],
["si","אם","ime"],
["milieu","אמצע","émtsa"],
["hier","אתמול","étmole"],
["sans (une personne)","בלעדי","biladéye"],
["durant/au cours de","במשך","béméchère"],
["à la fin","בסוף","basofe"],
["dans (+ mot de temps)","בעוד","béode"],
["environ","בערך","béérère"],
["problème","בעיה","baaya"],
["évidemment","בוודאי","bévadaye"],
["s'arranger","להסתדר","léhistadére"],
["organisation","הסתדרות","histadroute"],
["lamentable","אומלל","oumlâle"],
["lancer","לזרוק","lizrôke"],
["participer","להשתתף ב...","léhichtatéfe bé..."],
["participation","השתתפות","hichtatfoute"],
["regarder","להסתכל","léhistakéle"],
["regard","הסתכלות","histakloute"],
["file d'attente","תור","tore"],
["caisse (d'assurance/enregistreuse)","קופה","koupâ"],
["regretter","להצטער על","léhitstaére al"],
["regret","הצטערות","hitstaaroute"],
["logique","היגיון","higayône"],
["misérable/malheureux","מסכן","miskêne"],
["misère","מסכנות","miskénoûte"],
["rhume","נזלת","nazêléte"],
["progresser","להתקדם","léhitkadéme"],
["progrès","התקדמות","hitkadmoute"],
["utiliser/employer","להשתמש","léhichtaméche"],
["utilisation","שימוש","shimoushe"],
["parfum","בושם","bôsséme"],
["parfumer","לבשם","lévassême"],
["confondre/embrouiller","לבלבל","lévalbéle"],
["confusion/désordre","בלבול","bilboule"],
["sentir/humer/flairer","להריח","léhariakh"],
["odorat/flair","הרחה","harakha"],
["au contraire","להפך","lééfère"],
["contraire","הפך","éfère"],
["richesse","עושר","ochère"],
["riche","עשיר","achire"],
["bonheur","אושר","ochère"],
["recommander","להמליץ","léhamlitse"],
["heureux","מאושר","méouchar"],
["analyser","לנתח","lénatéakh"],
["souhaiter","לאחל ל","léarel lé"],
["égal","שווה","chavé"],
["ça vaut le coup","זה שווה","zé chavé"],
["comparer","להשוות בין","léachvot béine"],
["comparaison","השואה","hachvaa"],
["voeux/souhaits","אחול","iroule"],
["alors que...","ואילו","véyilou"],
["déprimé","מדוכא","médouka"],
["déprimer","לדכדך","lédardère"],
["déprimant","מדכא","médakê"],
["s'intéresser à","להתענין ב","léhit'an'yéne bé"],
["intérêt (sollicitude)","התענינות","hit'an'yénoute"],
["intéressé","מעוניין","mé'ounyâne"],
["intéresser","לעניין","lé'anyêne"],
["intérêt","עניין","inyâne"],
["forêt","יער","yâ'are"],
["fleuve","נחר","narâre"],
["fier","גאה","gué'ê"],
["fierté","גאווה","ga'avâ"],
["luxueux","מפואר","méfo'âre"],
["tourner/circuler","להסתובב","léhistovéve"],
["tournoiement","הסתובבות","histovévoute"],
["violence","אלימות","alimoute"],
["blagues","בדיחות","bdirote"],
["améliorer","לשפר","léchapére"],
["amélioration","שפור","chipoure"],
["s'organiser","להתארגן","léhitarguéne"],
["c'est préférable","עדיף","adife"],
["confiance en soi","ביטחון עצמי","bitarone atsmi"],
["courant (actuel)","שוטף","chotêfe"],
["choix (assortiment)","מבחר","mivrâre"],
["location","השכרה","haskarâ"],
["louer (propriétaire)","להשכיר","léaskîre"],
["lorsque/quand","כאשר","ka'achêre"],
["agence immobilière","סוכנות נדלן","sornoute nadlane"],
["probabilité (possibilité)","סיכוי","sikoûye"],
["emplacement","מיקום","mikoûme"],
["spectacle","הצגה","hatsagâ"],
["émotion (émoi)","ריגוש","rigoûche"],
["meublé","מרוהט","mérohâte"],
["appartement meublé","דירה מרוהטת","dirâ mérohêtéte"],
["domaine (d'activité)","תחום","troume"],
["ça vaut la peine","כדאי","quédaye"],
["avoir à (se forcer à)","מוכרח","moukhrare"],
["laitue","חסה","rassa"],
["factures","חשבונות","réchbonote"],
["impôts/taxes","מיסים","misime"],
["obligé (de)","חייב","rayâve"],
["autorisé","מותר","moutare"],
["influencer","להשפיע","léhachpia"],
["influence","השפעה","hachpaa"],
["décider","להחליט","léharlite"],
["décision","החלטה","harlata"],
["en-dessous","מתחת","mitarate"],
["sous","תחת","tarate"],
["envoûter/ensorceler","לכשף","lérachêfe"],
["attention !","זהירות","zéhiroûte"],
["idée","רעיון","ra'ayône"],
["se laver/se baigner","להתרחץ","léhitrarétse"],
["une de ces femmes","אחת הנשים","arate anachime"],
["cuillère","כף","kafe"],
["petite cuillère","כפית","kapîte"],
["couverture (de lit)","שמיכה","smirâ"],
["casserole","סיר","sire"],
["échelle","סולם","soulâme"],
["jouet","צעצוע","tsa'atsôu'a"],
["nettoyage","ניקוי","nikouille"],
["secouer","לנער","lénaére"],
["grimper","לטפס על","létapésse al"],
["escalade","טפוס","tipousse"],
["assembler/composer","להרכיב","léharkive"],
["assemblage/montage","הרכבה","harkava"],
["nettoyer","לנקות","lénakote"],
["laver","לרחוץ","lirrotse"],
["lavage","רחיצה","réritsa"],
["nabot/nain","ננס","nanâsse"],
["remercier","להודות","léhodôte"],
["tant que","כל עוד","kole ode"],
["figue","תאנה","té'énâ"],
["perdre","לאבד","léabéde"],
["perte","אבוד","iboude"],
["naître","להולד","léhivaléde"],
["France","צרפת","tsarfâte"],
["français","צרפתי","tsarfatî"],
["foutre le bordel","לברדק","lévardêke"],
["une bonne occasion","הזדמנות טובה","izdamnoute tova"],
["clarifier (expliquer)","לבאר","léva'êre"],
["en fait","בעצם","béétsème"],
["os","עצם","étsème"],
["par moi-même","בעצמי","béatsmi"],
["moi-même","עצמי","atsmi"],
["traiter/soigner","לטפל ב","létapéle bé"],
["traitement/soins","טפול","tipoule"],
["tuer","להרוג","laharoge"],
["meurtre","הריגה","hariga"],
["refuser","לסרב","léssaréve"],
["refus","סרוב","sérouve"],
["aimer/prendre plaisir à","להנות מ","léhanote mi"],
["plaisir","הנאה","hanaa"],
["gourmand","גרגרן","garguérâne"],
["gourmande","גרגרנית","garguérânite"],
["offrir/proposer","להציע","léhatsia"],
["proposition","הצעה","hatsaa"],
["employer/embaucher","להעסיק","léaasik"],
["qualité","איכות","éroute"],
["prévoir à l'avance/anticiper","לצפות מראש","litspote méroche"],
["regarder/observer/prévoir","לצפות","litspote"],
["observation","צפיה","tsfiya"],
["anticiper/antidater","להקדים","léhakdime"],
["introduction","הקדמה","hakdama"],
["attention/écoute","הקשבה","hakchava"],
["je m'en fiche","לא איכפת לי","lo irpate li"],
["erreur","טעות","taoute"],
["par erreur","בטעות","bétaoute"],
["remplacer","להחליף","léarlife"],
["convaincant/persuasif","משכנע","méchakhnê'a"],
["convaincre/persuader","לשכנע","léchakhnê'a"],
["persuasion","שכנוע","chikhnoua"],
["rouler (arnaquer quelqu'un)","לעבוד על","laavode al"],
["plutôt","דווקא","davka"],
["nuire/endommager","להזיק ל","léhazike"],
["lycée","תיכון","tirone"],
["verset","פסוק","passoûke"],
["source (fontaine)","מעיין","ma'ayâne"],
["amande","שקד","chakêde"],
["quantité","כמות","kamoûte"],
["courtoisie","נימוס","nimousse"],
["s'enfuir","לברוח","livroare"],
["fuite","בריחה","brira"],
["questionnaire","שאלון","ché'élône"],
["secrétaire (une)","מזכירה","mazkîra"],
["puisque/étant donné (que)","כיוון ש","kevân che-"],
["toutefois","אולם","oulame"],
["chier","לחרבן","lérarbéne"],
["casser/briser","לשבור","lichbore"],
["bris/cassement","שבירה","chvira"],
["brisé/cassé","שבור","chavoûre"],
["cacher","להסתיר","léhastire"],
["dissimulation","הסתרה","hastara"],
["pisser","להשתין","lahachtîne"],
["plaisanter","להתבדח","léhitbadê'ar"],
["réponse","תשובה","tchouvâ"],
["décrire; tracer","לתאר","létaére"],
["description","תאור","téoure"],
["adjectif","תואר","toare"],
["besoin (avoir)","זקוק","zakouk"],
["je m'en doutais","תיארתי לעצמי","tiyarti léatsmi"],
["par hasard","במקרה","bémikré"],
["demander/exiger","לדרוש","lidroche"],
["exigence","דרישה","dricha"],
["vieux","זקן","zaken"],
["sortir","לצאת","latséte"],
["sortie","יציאה","yétsia"],
["c'est rare","זה נדיר","zé nadîre"],
["proche (près)","סמוך","samoûkh"],
["évaluer/apprécier","להעריך","léhaarikh"],
["évaluation/appréciation","הערכה","haarakha"],
["en soi","מאליו","méélave"],
["gigantesque","מאליו","anakî"],
["bout (extrémité)","קצה","katsê"],
["attente (espoir)","ציפייה","tsipiyâ"],
["attente","המתנה","hamtanâ"],
["acte (action)","מעש","mâ'asse"],
["accoucher/mettre au monde","ללדת","lalédète"],
["naissance","לדה","léyda"],
["effacer","למחוק","limkhoke"],
["cheval","סוס","sousse"],
["parfait","מושלם","mouchlâme"],
["exposition","תערוכה","ta'aroukhâ"],
["sculpteur","פסל","passâle"],
["sculpture","פיסול","pissoûle"],
["créer","ליצור","litsore"],
["création","יצירה","yétsira"],
["animal","חיה","khayâ"],
["bien que","אף ש","afe ché"],
["si bien que","כך ש","kakh ché"],
["muscle","שריר","chrire"],
["musclé","שרירי","chrirî"],
["à peine","בקושי","békochi"],
["par contre","לעומת זאת","léoumate zote"],
["en effet","למעשה","lémaassé"],
["détail","פרט","prate"],
["grandeur (amplitude)","גודל","gôdéle"],
["narine","נחיר","nékhîre"],
["rigoureux","קפדני","kapdanî"],
["minutieux","קפדן","kapdâne"],
["mioche","פספוס","fasfoûsse"],
["queue (du chat)","זנב","zanâve"],
["enfoncer; investir","להשקיע","léhachkia"],
["enfoncement; investissement","השקעה","hachkaa"],
["forme (aspect)","צורה","tsourâ"],
["publique/audience","קהל","kahâle"],
["ajouter","להוסיף","léhossife"],
["ajout","הוספה","hossafa"],
["nichons","ציצים","tsîtsime"],
["cul","ישבן","yachvâne"],
["pendant que","בזמן ש","bézman ché"],
["poupée","בובה","boubâ"],
["souris","עכבר","akhbâre"],
["sourire","חיוך","khiyoûkh"],
["type","טיפוס","tipoûsse"],
["stupide","טיפש","tipêche"],
["affronter/se mesurer","להתמודד על, עם","léhitmodéde"],
["lutte, rivalité","התמודדות","hitmodédoute"],
["désirer","לחפוץ","lakhpotse"],
["désir","חפיצה","khafitsa"],
["quitter","לעזוב","laazove"],
["départ (abandon)","עזיבה","aziva"],
["départ","יציאה","yêtsi'â"],
["départ (course)","זינוק","zinoûke"],
["sauter","לקפוץ","likpotse"],
["saut","קפיצה","kfitsa"],
["vente","מכירה","mekhira"],
["démolir","להרוס","laharosse"],
["démolition","הריסה","harissa"],
["avant-hier","שלשום","chilchôme"],
["miracle","נס","nesse"],
["miraculeux","נסי","nissî"],
["prince","נסיך","nassikh"],
["princesse","נסיכה","néssikhâ"],
["adolescent","מתבגר","mitbaguêre"],
["adolescence","בגרות","bagroûte"],
["admirer","להתפעל","léhitpaéle"],
["admiration","התפעלות","hitpaaloute"],
["adorer","לסגוד","lisgôde"],
["adoration","סגידה","sguidâ"],
["après-demain","מחרתיים","makharatâyime"],
["inspiration","השראה","hachraah"],
["l'essentiel/principalement","בעיקר","bé'ikar"],
["essentiel","עיקרי","ikarî"],
["espérer","לקוות","lékavote"],
["espoir","תקוה","tikva"],
["essayer","לנסות","lénassote"],
["ethnie","עדה","édâ"],
["origine","מוצא","motsâ"],
["prêt (de fonds)","הלואה","halva'â"],
["prêter","להלוות","léhalvote"],
["passer la nuit (dormir)","ללון","laloune"],
["mordre","לנשוך","linchôkh"],
["gaspiller/dépenser","לבזבז","lévazbéze"],
["gaspillage/perte","בזבוז","bizbouze"],
["valise","מזוודה","mizvadâ"],
["quoi de neuf?","מה איתך","ma itar/itra"],
["sembler","להיראות","léhéra'ôte"],
["semblable (comme)","דומה","domê"],
["il pouvait","היה יכול","aya yakhol"],
["elle pouvait","היתה יכולה","ayéta yékhola"],
["ils pouvaient","היו יכולים","ayou yékholim"],
["elles pouvaient","היו יכולות","ayou yékholote"],
["invitée","אורחת","orakhat"],
["passer; transgresser","לעבור","laavore"],
["faute/contravention","עברה","avera"],
["considérer","לשקול","lichkôle"],
["être considéré","להחשב ל","léhékhachêve lé"],
["considération","שיקול","chikoûle"],
["identifier","לזהות","lézahôte"],
["identique","זהה","zéhê"],
["identification","זיהוי","zihoûye"],
["bâtard","ממזר","mamzêre"],
["gribouiller; papoter","לקשקש","lékachkêche"],
["bavarder, papoter","לפטפט","léfatpête"],
["conscient","הכרתי","hakaratî"],
["connaissance, reconnaissance","הכרה","hakara"],
["connaître, reconnaître","להכיר","léhakire"],
["sang","דם","dame"],
["cerveau","מוח","mô'akh"],
["flot (abondance)","שטף","chêtéfe"],
["hémorragie","שטף דם","chêtéfe dame"],
["infatigable (m.)","בלתי נלאה","biltî nil'ê"],
["infatigable (f.)","בלתי נלאית","biltî nil'êite"],
["stylo","עט","éte"],
["papier","נייר","néyâre"],
["dessiner/noter","לרשום","lirchome"],
["liste","רשימה","rechimâ"],
["porc","חזיר","khazîre"],
["malgré","אף-על-פי","af al pi"],
["présentateur (tv, radio)","שדרן","chadrâne"],
["rôle","תפקיד","tafkîde"],
["titre","כותרת","kotêréte"],
["agir; fonctionner","לפעול","lif'ole"],
["action","פעולה","péoula"],
["consommation de viande","אכילת בשר","akhilat bassar"],
["entre autre","בין השאר","béne hachéare"],
["réduire","לצמצם","létsamtséme"],
["réduction","צמצום","tsimtsoume"],
["souffrance","סבל","sêvéle"],
["pollution","זיהום","zihoûme"],
["causer (provoquer)","לגרום","ligrome"],
["action de causer","גרימה","grima"],
["industrie","תעשייה","ta'assiyâ"],
["un pas","צעד אחד","tsâ'ade ékhad"],
["lire; appeler; nommer","לקרוא","likro"],
["cri; exclamation; appel","קריאה","kriya"],
["parce que","מכיוון","mikévâne"],
["publier","לפרסם","léfarsême"],
["rapidement","במהירות","biméhiroûte"],
["vitesse","מהירות","méhiroûte"],
["aujourd'hui (actuellement)","כיום","kayôme"],
["inventer","להמציא","léhamtsi"],
["invention","המצאה","hamtsaa"],
["rejoindre","להצטרף","léhitstarêfe"],
["recette (cuisine)","מתכון","matkône"],
["végétarien","צמחוני","tsimkhonî"],
["au profit de... (en faveur de)","לטובת","létovâte"],
["complet/entier","שלם","chalême"],
["servir (à table)","להגיש","léhaguîche"],
["plat (mets)","מנה","manâ"],
["environnement","סביבה","svivâ"],
["être envoyé","להשלח","léhichalakh"],
["terroriste","מחבל","mékhabêle"],
["être fermé","להסגר","léhisaguère"],
["coq","תרנגול","tarnégôle"],
["poule","תרנגולת","tarnégôléte"],
["volaille/poulet","עוף","ofe"],
["rat","עכברוש","akhberôche"],
["oiseau","ציפור","tsipôre"],
["fourmi","נמלה","némalâ"],
["cafard","ג'וק","djouke"],
["canard","ברווז","barvâze"],
["bovins","בקר","bakâre"],
["boeuf","שור","chore"],
["moustique","יתוש","yatoûche"],
["mouche","זבוב","zvouve"],
["abeille","דבורה","dvorâ"],
["élever (cultiver)/soigner (s'occuper)","לטפח","létapê'akh"],
["remplir","למלא","lémalé"],
["remplissage","מלוי","milouille"],
["spécialiste","מומחה","moumkhê"],
["demande (économie)","ביקוש","bikoûche"],
["demande","בקשה","bakachâ"],
["approvisionnement/livraison","הספקה","haspaka"],
["cesser/interrompre","להפסיק","léhafsike"],
["cessation/interruption/pause","הפסקה","hafsaka"],
["exagérer","להפריז","léhafrize"],
["exagération","הפרזה","hafraza"],
["défendre","להגן","léhaguene"],
["défense/protection","הגנה","hagana"],
["est-ce que?","האם","ha'ime"],
["humeur/état d'âme","מצב רוח","matsâve roû'akh"],
["cuir au four/faire de la pâtisserie","לאפות","lééfote"],
["cuisson au four","אפיה","afiya"],
["totalement","לגמרי","légamrê"],
["vide","ריק","rike"],
["menteur","שקרן","chakrâne"],
["menteuse","שקרנית","chakrânite"],
["mentir","לשקר","léchakére"],
["mensonge","שקור","chikoure"],
["dessiner/peindre","לציר","létsayere"],
["dessin/peinture","ציור","tsiyure"],
["haïr/détester","לשנוא","lisno"],
["haine/hostilité","שנאה","sin'a"],
["frontière","גבול","gvoule"],
["commun","משותפ","méchoutâfe"],
["disons que ...","נגיד ש","naguide ché"],
["distribuer","לחלק","lékhalêke"],
["distribuer (les rôles)","ללהק","lélahêke"],
["distribution","חלוקה","khaloukâ"],
["distribution (casting)","ליהוק","lihoûke"],
["tigre","נמר","namêre"],
["tigresse","נמרה","némérâ"],
["terrible (m)","נוראי","nora'î"],
["terrible (f)","נוראית","nora'ît"],
["infrastructure","תשתית","tachtîte"],
["feux d'artifice","זיקוקים","zikoukime"],
["parrallèle","מקביל","makbile"],
["plusieurs choses à la fois","כמה דברים במקביל","kama dvarim bémakbile"],
["formulaire","טופס","tôfésse"],
["le jeton est descendu","האסימון ירד","aasimône yarade"],
["lourd","כבד","kavêde"],
["ver à soie","תולעת משי","tolâ'ate mêchi"],
["araignée","עכביש","akavîche"],
["nous tous","כולנו","koulanou"],
["fil","חוט","khoute"],
["fer","ברזל","barzêle"],
["sérieusement (avec sérieux)","ברצינות","birétsinoûte"],
["extérieur","חיצוני","khitsonî"],
["nuage","ענן","anâne"],
["géant","ענק","anâke"],
["arriver (se produire)","לקרות","likrôte"],
["endommager/faire du mal","לפגוע","lifgô'a"],
["confortable/commode","נוח","nô'akh"],
["supplice","עינוי","inoûye"],
["aucun","שום","choume"],
["rien","כלום","kloume"],
["ivre (m)","שתוי","chatoûye"],
["ivre (f)","שתויה","chatoûya"],
["finition","גימור","guimoûre"],
["couloir","מסדרון","misdérône"],
["cheville (anatomie)","קרסול","karsôle"],
["aller-retour","הלוך-חזור","alokh-khazor"],
["foudre","ברק","barâke"],
["ramer","לחתור","lakhtôre"],
["restriction","הגבלה","hagbalâ"],
["produit (de consommation)","מוצר","moutsâre"],
["vomir","להקיא","léhaki"],
["vomissement","הקאה","hakaa"],
["visage","פנים","panîme"]];*/
                
var default_words = [["manifester","להפגין",""],
["en attendant","ביינתים",""],
["j'en ai marre","נמאס לי",""],
["immédiatement","מייד",""],
["je suis en colère","אני כועס",""],
["tasse","כוס",""],
["jaloux","קנאי",""],
["compétition","תחרות",""],
["manifestation","הפגנה",""],
["tu me manques","אני מתגעגע לך",""],
["cuisine","מטבח",""],
["rouge","אדום",""],
["simplement","פשוט",""],
["couverts/outils","כלים",""],
["dense/surpeuplé","צפוף",""],
["couleur","צבע",""],
["couleurs","צבעים",""],
["aider à","לעזור ל...",""],
["il n'a pas le choix","אין לו בריחה",""],
["en forme","בכושר",""],
["réussir","להצליח",""],
["il y a longtemps","מזמן","mizman"],
["tromper/trahir","לבגוד","livgod"],
["épisode/chapitre","פרק","pereq"],
["se rencontrer","להפגש עם","léhipaguesh im"],
["message","הודעה","odaa"],
["terminer","לסיים",""],
["se séparer","להפרד","léhipared"],
["chanteur","זמר","zamar"],
["il la drague","הוא מתחיל איתה",""],
["elle est folle de lui","היא משוגעת עליו",""],
["surpris/étonné","מופתע","moufta"],
["abricot","משמש","michmech"],
["fini","נגמר",""],
["célèbre","מפורסם",""],
["poivron","פלפל",""],
["vraiment","ממש",""],
["désert","מדבר",""],
["peau","עור",""],
["astuce/truc","הקונץ",""],
["invité","אורח","orêakh"],
["distance","מרחק",""],
["profession","מקצוע","miktsoa"],
["médecin","רופא",""],
["lumière","אור",""],
["train","רכבת",""],
["choisir","לבחר","livkhor"],
["louer (de)","לשכור","liskore"],
["vérifier","לבדוק","livdoke"],
["mesurer","למדוד","limdode"],
["partenaire","שותף","choutafe"],
["vendre","למכור","limkore"],
["finir","לגמור","ligmore"],
["les employés","העובדים",""],
["ouvrir","לפתוח","liftoakh"],
["se réjouir","לשמוח","lismoakh"],
["envoyer/poster","לשלוח ל...","lichloakh"],
["oublier","לשכוח","lichcoakh"],
["entretien d'embauche","ראיון עבודה","réayone avoda"],
["déterminer/fixer","לקבוע","likboa"],
["candidat","מועמד","mou'amade"],
["nager","לשחות","lisrote"],
["piscine","בריכה","brékha"],
["signer","לחתום על","laratome"],
["partie (négociations)","צד","tsade"],
["parties (négociations)","צדדים",""],
["accord","הסכם","héskême"],
["ministre","שר","sare"],
["défense","ביטחון",""],
["arrêter (cesser)","לעצור","la'atsôre"],
["passage piétons","מעבר החצייה",""],
["croire","להאמין","léha'amîne"],
["dégoûter","להגעיל את","léhag'île"],
["être dégoûté","להיגעל מ","léhiga'êle mi"],
["âne","חמור","ramôre"],
["tourner/s'adresser/donner sur","לפנות","lifnote"],
["éducation","חינוך","rinour"],
["je me bat contre moi","אני נלחם בעצמי","ani nilrame betsmi"],
["salle de sport","מכון כושר","marone kocher"],
["concentration","ריכוז","ricouze"],
["rater","לפספס","lefasfess"],
["rire","לצחוק","litsroque"],
["se moquer de","לצחוק על","litsroque al"],
["enquête","תחקיר","tarkire"],
["évènement","אירוע","eyroua"],
["globe terrestre","כדור הארץ","cadour aarets"],
["rond","עגול","agole"],
["plat","שטוח","chatouare"],
["être d'accord","להסכים","léaskime"],
["président (PDG)","מנכל","mankale"],
["demander à","לבקש מ","levakesh mi"],
["lieux de divertissement","מקומות בילוי","mékomote bilouye"],
["passer du bon temps","לבלות","levalote"],
["se transformer","להשתנות","léhichtanote"],
["changer/modifier","לשנות","léchanote"],
["tu as raison","אתה צודק","ata tsodek"],
["personnage","דמות","dmoute"],
["différent","שונה","choné"],
["sérieux","רציני","rétsini"],
["honte","בושה","bousha"],
["comportement","התנהגות","hitnahagoute"],
["se comporter","להתנהג","léhitnaègue"],
["groupe (bande)","להקה","léhaka"],
["organiser","לארגן","léarguène"],
["étoile","כוכב","corave"],
["punition","עונש","onèche"],
["jeu","משחק","misrak"],
["diplôme","תעודה","téouda"],
["ça va pas, jamais de la vie !","מה פתאום","ma pitome"],
["équipe","צוות","tsévette"],
["tenir","להחזיק","léarzik"],
["trouver","למצוא","limtso"],
["fleur","פרח","pérar"],
["manger","לאכול","léérole"],
["loi","חוק","rok"],
["dis moi","תגיד לי","taguide li"],
["pleurer","לבכות","livcote"],
["bientôt","עוד מעט","ode méate"],
["il n'y a pas de quoi","אין בעד מה","eyn béad ma"],
["beaucoup","המון","amone"],
["avant","קודם","kodème"],
["plus tard","אחר כך","arar kar"],
["il faut/avoir besoin de","צריך","tsarir"],
["patience","סבלנות","savlanoute"],
["malgré/bien que","למרות","lamrote"],
["tempêtes de sable","סופות חול","sofot role"],
["brume","אובך","ovère"],
["farine","קמח","quémar"],
["oignon","בצל","batsal"],
["huile","שמן","chémène"],
["gras","שמן","chamène"],
["mince","רזה","razé"],
["graisse","שומן","choumane"],
["concombre","מלפפון","mélaféfone"],
["tomate","עגבניה","agvanya"],
["plante","צמח","tsémar"],
["cactus","צבר","tsabar"],
["menthe (mot arabe)","נענע","nana"],
["menthe","מנטה","mènta"],
["carotte","גזר","guézer"],
["ainsi","כך","car"],
["donation","נתינה","nétina"],
["volontaires/bénévoles","מתנדבים","mitnadvime"],
["une visite","ביקור","bikouve"],
["j'ai la grippe","אני מצונן","ani metsounane"],
["vieillir","להזדקן","léhizdaquène"],
["être photographié","להצטלם","léhitsatélem"],
["être appelé au téléphone","להתקשר","léhitkasher"],
["prendre froid","להצטנן","léhitstanène"],
["pauvre","עני","ani"],
["généreux/philanthrope","נדיב","nadiv"],
["générosité","נדיבות","ndivout"],
["minorité","מיעוט","miout"],
["journal intime","יומן","iomane"],
["cette année","השנה","achana"],
["adulte","מבוגר","mévougar"],
["ennuyeux","משעמם","méchaamem"],
["charge/fardeau","נטל","nétèl"],
["constitution","חוקה","rouka"],
["crashé (whatsapp a crashé)","קורס","korès"],
["condition/état","תנאי","ténayi"],
["conditions (de vie)","תנאים","ténayime"],
["pastèque","אבטיח","avatyar"],
["embrasser","לנשק","lénachèque"],
["aéroport","שדה התעופה","sédé atéoufa"],
["je me sépare","אני ניפרד","ani nifrade"],
["se cacher","להסתתר","léhistatère"],
["complexe/compliquée (fille)","מורכבת","mourkévéte"],
["balance","מאזנים","moznayime"],
["complexe (garçon)","מורכב","mourkâve"],
["complexité","מורכבות","mourkavoûte"],
["construire un logiciel","לבנות תוכנה","livnote torna"],
["période d'essai","תקופת נסיון","tékoufate nissayone"],
["prendre en photo","לצלם","létsalème"],
["photocopie","צילום","tsiloume"],
["promotion","קידום","quidoume"],
["gagner","להרוויח","léarviare"],
["être en colère","לכעוס","lirosse"],
["se coucher","לשכב","lichkâve"],
["courage","אומץ","ometsse"],
["courageux","אמיץ","amîtsse"],
["courageuse","אמיצה","amîtssa"],
["conduire","לנהוג","linogue"],
["s'inquiéter","לדאג ל...","lidogue"],
["inquiétude/souci","דאגה","déaga"],
["inquiéter/causer des soucis","להדאיג","léhadigue"],
["rester","להישאר","léhichaère"],
["différence","הבדל","évdèle"],
["possibilités d'évolution","אפשרויות קדום","efcharouiote quidoume"],
["entreprise","חברה","révra"],
["analyste (informatique)","מנתח","ménatéra"],
["culot","חוצפה","routspa"],
["charme","קסם","kêsséme"],
["poubelle/ordure","זבל","zével"],
["c'est un droit","זאת זכות","zot zroute"],
["j'ai le droit","זכותי","zrouti"],
["dessin animé","סרט מצויר","seret metsouyar"],
["c'est génial ! Top !","חבל על הזמן","raval al azmane"],
["lapin","שפן","chafane"],
["autruche","בת יענה","bat yahana"],
["autruches","בנות יענה","banote yahana"],
["bâton","מקל","maquel"],
["toucher","לגעת","lagaate"],
["attraper","לתפוס","litposse"],
["résoudre","לפתור","liftore"],
["tirer/retirer (de l'argent)","למשוך","limchore"],
["policier","שוטר","chotere"],
["réalité","מציאות","métsiyoute"],
["découvrir","לגלות","légalote"],
["par coeur","בעל פה","béal pé"],
["remarquer/faire attention","לשים לב","lasime lève"],
["gênant","לא נעים","lo naime"],
["stratégie","אסטרטגיה","astratégia"],
["action (part)","מניה","ménaya"],
["sifflement","שריקה","shrika"],
["allumer","להדליק","léhadlique"],
["habiller","להלביש","léhalbiche"],
["enregistrer","להקליט","léhaklite"],
["laisser","להשאיר","léhachire"],
["promettre","להבטיח","léhavtiare"],
["insérer","להכניס","léharnisse"],
["expliquer","להסביר","léhasbire"],
["contrat","חוזה","rozé"],
["électricité","חשמל","rachmale"],
["locataire","דייר","dayare"],
["pire","יותר גרוע","yoter garoua"],
["niveau","רמה","rama"],
["lorsque","כש...","qché..."],
["pour/dans le but","כדי","quédey"],
["suffire (réussir à temps)","להספיק","léaspik"],
["solution","פתרון","pitarone"],
["solutions","פתרונות","pitronote"],
["quel culot !","איזו חוצפה !","eizo routspa !"],
["direct","ישיר","yachir"],
["le moins pire","הרע במיעוטו","ara bimiyouto"],
["but/objectif","מטרה","matara"],
["juge (un)","שופט","chofète"],
["voter/pointer du doigt","להצביע","léatsbiya"],
["en général/habituellement","בדרך כלל","bédérere rlal"],
["droit","ישר","yachar"],
["vrai","אמיתי","amiti"],
["nord","צפון","tsafone"],
["sud","דרום","darome"],
["est (orientation)","מזרח","mizrare"],
["ouest","מערב","maarave"],
["date","תאריך","taarir"],
["agence juive","סוכנות היהודית","sournoute hyéoudite"],
["avantage","יתרון","yitarone"],
["promesse","הבטחה","havtara"],
["en bas","למטה","lémata"],
["haut","גבוה","gavôa"],
["se précipiter","למהר","lémaer"],
["annuler","לבטל","lévatel"],
["licencier","לפטר","léfatére"],
["raccrocher/rompre le lien","לנתק","lénatek"],
["cuisiner","לבשל","lévachel"],
["fumer","לעשן","léachen"],
["jouer (un instrument)","לנגן","lénaguène"],
["directeur","מנהל","ménahèle"],
["expérience (travail)","ניסיון","nissayone"],
["salaire","משכורת","mascorète"],
["recommandation","המלצה","hamlatsa"],
["emploi à mi-temps","חצי משרה","retsi misra"],
["emploi à temps plein","משרה מלאה","misra méléa"],
["formation (études)","השכלה","haskala"],
["langue (langage)","שפה","safa"],
["curriculum vitae","קורות חיים","quorote rayime"],
["ingénieur","מהנדס","méandès"],
["situation familiale","מצב משפחתי","matsave mishparti"],
["marié","נשוי","nassouille"],
["célibataire","רווק","ravak"],
["tu me prends pour qui ? (m)","מה אני נראה לך ?","ma ani nira lar"],
["tu me prends pour qui ? (f)","מה אני נראית לך ?","ma ani nirét lar"],
["code secret","קוד סודי","code sodi"],
["chiffre","ספרה","sifra"],
["faire une faveur/rendre service","לעשות טובה","laassote tova"],
["faveur/service","טובה","tova"],
["sécurité routière","פטיחות בדרכים","pétiroute badrarime"],
["force","כוח","coar"],
["publicité","פרסומת","pirsomète"],
["stage","קורס","course"],
["tiroir","מגרה","méguéra"],
["réchauffer","להתחמם","léhitramème"],
["refroidir","להתקרר","léhitquarère"],
["carosse","מרכבה","mercava"],
["muraille","חומה","roma"],
["site de rencontre","אתר הכרויות","atar érrouyote"],
["en même temps/simultanément","תוך כדי","tor quédey"],
["faire monter","להעלות","léaalote"],
["ascenceur","מעלית","maalite"],
["éclater (de rire)/ pénétrer (par effraction)","לפרוץ","lifrotse"],
["devant toi","לפניך","léfanira"],
["impatient","חסר סבלנות","rassar savlanoute"],
["du tout","בכלל","birlal"],
["manquant","חסר","rassère"],
["direction (sens)","כיוון","kivoune"],
["envers","כלפי","clapi"],
["envers moi","כלפיי","clapye"],
["circonstances","נסיבות","nésibote"],
["dérangement","הפרעה","afra'a"],
["déranger","להפריע","léhafri'a"],
["apporter/emmener","להביא","léhabia"],
["se tenir debout","לעמוד","laamode"],
["avis","דעה","déa"],
["à mon avis","לדעתי","lédaati"],
["écouter","להקשיב","léakchive"],
["larmes","דמעות","dimaote"],
["peu à peu/petit à petit","בהדרגה","béhadraga"],
["remettre (un message)","למסור","limsore"],
["requête/tournant","פניה","pniya"],
["bureau (administration)","לשכה","lichka"],
["bureau de l'emploi","לשכת התעסוקה","lichkat ataasouqua"],
["effraction","פריצה","pritsa"],
["art","אומנות","omanoute"],
["alors","אז","az"],
["frère","אח","ar"],
["en arrière","אחורה","arora"],
["soeur","אחות","arote"],
["soeurs","אחיות","arayote"],
["neveu","אחיין","aryane"],
["nièce","אחיינית","aryanite"],
["autre","אחר","arère"],
["dernier","אחרון","ararone"],
["nourriture","אוכל","orèle"],
["oreille","אוזן","ozène"],
["ambiance/atmosphère","אווירה","avira"],
["amour","אהבה","ahava"],
["légende","אגדה","agada"],
["air","אוויר","avir"],
["vérité","אמת","émète"],
["au-dessus","מעל","méal"],
["réfrigérateur","מקרר","makrère"],
["police","משטרה","michtara"],
["enfin","סוף סוף","sof sof"],
["interdit","אסור","asour"],
["nez","אף","af"],
["personne","אף אחד","af érade"],
["même","אפילו","afilou"],
["doigt","אצבע","étsba"],
["long","ארוך","arore"],
["feu","אש","èche"],
["gris","אפור","afore"],
["correspondre (par letttes)","להתכתב","léhitkatève"],
["peut-être","אולי","oulaye"],
["armoire","ארון","arone"],
["après-midi","אחרי הצהריים","araraye atsaarayime"],
["quel","איזה","eyzé"],
["comment","איך","èrre"],
["il n'y a pas","אין","eyne"],
["quelle","איזו","eyzo"],
["vers, à...","אל","èle"],
["quels (quelles)","אילו","eylou"],
["ce sont","אלה","élé"],
["(ne...) mais...","אלא","éla"],
["si","אם","ime"],
["milieu","אמצע","émtsa"],
["hier","אתמול","étmole"],
["sans (une personne)","בלעדי","biladéye"],
["durant/au cours de","במשך","béméchère"],
["à la fin","בסוף","basofe"],
["dans (+ mot de temps)","בעוד","béode"],
["environ","בערך","béérère"],
["problème","בעיה","baaya"],
["évidemment","בוודאי","bévadaye"],
["s'arranger","להסתדר","léhistadére"],
["organisation","הסתדרות","histadroute"],
["lamentable","אומלל","oumlâle"],
["lancer","לזרוק","lizrôke"],
["participer","להשתתף ב...","léhichtatéfe bé..."],
["participation","השתתפות","hichtatfoute"],
["regarder","להסתכל","léhistakéle"],
["regard","הסתכלות","histakloute"],
["file d'attente","תור","tore"],
["caisse (d'assurance/enregistreuse)","קופה","koupâ"],
["regretter","להצטער על","léhitstaére al"],
["regret","הצטערות","hitstaaroute"],
["logique","היגיון","higayône"],
["misérable/malheureux","מסכן","miskêne"],
["misère","מסכנות","miskénoûte"],
["rhume","נזלת","nazêléte"],
["progresser","להתקדם","léhitkadéme"],
["progrès","התקדמות","hitkadmoute"],
["utiliser/employer","להשתמש","léhichtaméche"],
["utilisation","שימוש","shimoushe"],
["parfum","בושם","bôsséme"],
["parfumer","לבשם","lévassême"],
["confondre/embrouiller","לבלבל","lévalbéle"],
["confusion/désordre","בלבול","bilboule"],
["sentir/humer/flairer","להריח","léhariakh"],
["odorat/flair","הרחה","harakha"],
["au contraire","להפך","lééfère"],
["contraire","הפך","éfère"],
["richesse","עושר","ochère"],
["riche","עשיר","achire"],
["bonheur","אושר","ochère"],
["recommander","להמליץ","léhamlitse"],
["heureux","מאושר","méouchar"],
["analyser","לנתח","lénatéakh"],
["souhaiter","לאחל ל","léarel lé"],
["égal","שווה","chavé"],
["ça vaut le coup","זה שווה","zé chavé"],
["comparer","להשוות בין","léachvot béine"],
["comparaison","השואה","hachvaa"],
["voeux/souhaits","אחול","iroule"],
["alors que...","ואילו","véyilou"],
["déprimé","מדוכא","médouka"],
["déprimer","לדכדך","lédardère"],
["déprimant","מדכא","médakê"],
["s'intéresser à","להתענין ב","léhit'an'yéne bé"],
["intérêt (sollicitude)","התענינות","hit'an'yénoute"],
["intéressé","מעוניין","mé'ounyâne"],
["intéresser","לעניין","lé'anyêne"],
["intérêt","עניין","inyâne"],
["forêt","יער","yâ'are"],
["fleuve","נחר","narâre"],
["fier","גאה","gué'ê"],
["fierté","גאווה","ga'avâ"],
["luxueux","מפואר","méfo'âre"],
["tourner/circuler","להסתובב","léhistovéve"],
["tournoiement","הסתובבות","histovévoute"],
["violence","אלימות","alimoute"],
["blagues","בדיחות","bdirote"],
["améliorer","לשפר","léchapére"],
["amélioration","שפור","chipoure"],
["s'organiser","להתארגן","léhitarguéne"],
["c'est préférable","עדיף","adife"],
["confiance en soi","ביטחון עצמי","bitarone atsmi"],
["courant (actuel)","שוטף","chotêfe"],
["choix (assortiment)","מבחר","mivrâre"],
["location","השכרה","haskarâ"],
["louer (propriétaire)","להשכיר","léaskîre"],
["lorsque/quand","כאשר","ka'achêre"],
["agence immobilière","סוכנות נדלן","sornoute nadlane"],
["probabilité (possibilité)","סיכוי","sikoûye"],
["emplacement","מיקום","mikoûme"],
["spectacle","הצגה","hatsagâ"],
["émotion (émoi)","ריגוש","rigoûche"],
["meublé","מרוהט","mérohâte"],
["appartement meublé","דירה מרוהטת","dirâ mérohêtéte"],
["domaine (d'activité)","תחום","troume"],
["ça vaut la peine","כדאי","quédaye"],
["avoir à (se forcer à)","מוכרח","moukhrare"],
["laitue","חסה","rassa"],
["factures","חשבונות","réchbonote"],
["impôts/taxes","מיסים","misime"],
["obligé (de)","חייב","rayâve"],
["autorisé","מותר","moutare"],
["influencer","להשפיע","léhachpia"],
["influence","השפעה","hachpaa"],
["décider","להחליט","léharlite"],
["décision","החלטה","harlata"],
["en-dessous","מתחת","mitarate"],
["sous","תחת","tarate"],
["envoûter/ensorceler","לכשף","lérachêfe"],
["attention !","זהירות","zéhiroûte"],
["idée","רעיון","ra'ayône"],
["se laver/se baigner","להתרחץ","léhitrarétse"],
["une de ces femmes","אחת הנשים","arate anachime"],
["cuillère","כף","kafe"],
["petite cuillère","כפית","kapîte"],
["couverture (de lit)","שמיכה","smirâ"],
["casserole","סיר","sire"],
["échelle","סולם","soulâme"],
["jouet","צעצוע","tsa'atsôu'a"],
["nettoyage","ניקוי","nikouille"],
["secouer","לנער","lénaére"],
["grimper","לטפס על","létapésse al"],
["escalade","טפוס","tipousse"],
["assembler/composer","להרכיב","léharkive"],
["assemblage/montage","הרכבה","harkava"],
["nettoyer","לנקות","lénakote"],
["laver","לרחוץ","lirrotse"],
["lavage","רחיצה","réritsa"],
["nabot/nain","ננס","nanâsse"],
["remercier","להודות","léhodôte"],
["tant que","כל עוד","kole ode"],
["figue","תאנה","té'énâ"],
["perdre","לאבד","léabéde"],
["perte","אבוד","iboude"],
["naître","להולד","léhivaléde"],
["France","צרפת","tsarfâte"],
["français","צרפתי","tsarfatî"],
["foutre le bordel","לברדק","lévardêke"],
["une bonne occasion","הזדמנות טובה","izdamnoute tova"],
["clarifier (expliquer)","לבאר","léva'êre"],
["en fait","בעצם","béétsème"],
["os","עצם","étsème"],
["par moi-même","בעצמי","béatsmi"],
["moi-même","עצמי","atsmi"],
["traiter/soigner","לטפל ב","létapéle bé"],
["traitement/soins","טפול","tipoule"],
["tuer","להרוג","laharoge"],
["meurtre","הריגה","hariga"],
["refuser","לסרב","léssaréve"],
["refus","סרוב","sérouve"],
["aimer/prendre plaisir à","להנות מ","léhanote mi"],
["plaisir","הנאה","hanaa"],
["gourmand","גרגרן","garguérâne"],
["gourmande","גרגרנית","garguérânite"],
["offrir/proposer","להציע","léhatsia"],
["proposition","הצעה","hatsaa"],
["employer/embaucher","להעסיק","léaasik"],
["qualité","איכות","éroute"],
["prévoir à l'avance/anticiper","לצפות מראש","litspote méroche"],
["regarder/observer/prévoir","לצפות","litspote"],
["observation","צפיה","tsfiya"],
["anticiper/antidater","להקדים","léhakdime"],
["introduction","הקדמה","hakdama"],
["attention/écoute","הקשבה","hakchava"],
["je m'en fiche","לא איכפת לי","lo irpate li"],
["erreur","טעות","taoute"],
["par erreur","בטעות","bétaoute"],
["remplacer","להחליף","léarlife"],
["convaincant/persuasif","משכנע","méchakhnê'a"],
["convaincre/persuader","לשכנע","léchakhnê'a"],
["persuasion","שכנוע","chikhnoua"],
["rouler (arnaquer quelqu'un)","לעבוד על","laavode al"],
["plutôt","דווקא","davka"],
["nuire/endommager","להזיק ל","léhazike"],
["lycée","תיכון","tirone"],
["verset","פסוק","passoûke"],
["source (fontaine)","מעיין","ma'ayâne"],
["amande","שקד","chakêde"],
["quantité","כמות","kamoûte"],
["courtoisie","נימוס","nimousse"],
["s'enfuir","לברוח","livroare"],
["fuite","בריחה","brira"],
["questionnaire","שאלון","ché'élône"],
["secrétaire (une)","מזכירה","mazkîra"],
["puisque/étant donné (que)","כיוון ש","kevân che-"],
["toutefois","אולם","oulame"],
["chier","לחרבן","lérarbéne"],
["casser/briser","לשבור","lichbore"],
["bris/cassement","שבירה","chvira"],
["brisé/cassé","שבור","chavoûre"],
["cacher","להסתיר","léhastire"],
["dissimulation","הסתרה","hastara"],
["pisser","להשתין","lahachtîne"],
["plaisanter","להתבדח","léhitbadê'ar"],
["réponse","תשובה","tchouvâ"],
["décrire; tracer","לתאר","létaére"],
["description","תאור","téoure"],
["adjectif","תואר","toare"],
["besoin (avoir)","זקוק","zakouk"],
["je m'en doutais","תיארתי לעצמי","tiyarti léatsmi"],
["par hasard","במקרה","bémikré"],
["demander/exiger","לדרוש","lidroche"],
["exigence","דרישה","dricha"],
["vieux","זקן","zaken"],
["sortir","לצאת","latséte"],
["sortie","יציאה","yétsia"],
["c'est rare","זה נדיר","zé nadîre"],
["proche (près)","סמוך","samoûkh"],
["évaluer/apprécier","להעריך","léhaarikh"],
["évaluation/appréciation","הערכה","haarakha"],
["en soi","מאליו","méélave"],
["gigantesque","מאליו","anakî"],
["bout (extrémité)","קצה","katsê"],
["attente (espoir)","ציפייה","tsipiyâ"],
["attente","המתנה","hamtanâ"],
["acte (action)","מעש","mâ'asse"],
["accoucher/mettre au monde","ללדת","lalédète"],
["naissance","לדה","léyda"],
["effacer","למחוק","limkhoke"],
["cheval","סוס","sousse"],
["parfait","מושלם","mouchlâme"],
["exposition","תערוכה","ta'aroukhâ"],
["sculpteur","פסל","passâle"],
["sculpture","פיסול","pissoûle"],
["créer","ליצור","litsore"],
["création","יצירה","yétsira"],
["animal","חיה","khayâ"],
["bien que","אף ש","afe ché"],
["si bien que","כך ש","kakh ché"],
["muscle","שריר","chrire"],
["musclé","שרירי","chrirî"],
["à peine","בקושי","békochi"],
["par contre","לעומת זאת","léoumate zote"],
["en effet","למעשה","lémaassé"],
["détail","פרט","prate"],
["grandeur (amplitude)","גודל","gôdéle"],
["narine","נחיר","nékhîre"],
["rigoureux","קפדני","kapdanî"],
["minutieux","קפדן","kapdâne"],
["mioche","פספוס","fasfoûsse"],
["queue (du chat)","זנב","zanâve"],
["enfoncer; investir","להשקיע","léhachkia"],
["enfoncement; investissement","השקעה","hachkaa"],
["forme (aspect)","צורה","tsourâ"],
["publique/audience","קהל","kahâle"],
["ajouter","להוסיף","léhossife"],
["ajout","הוספה","hossafa"],
["nichons","ציצים","tsîtsime"],
["cul","ישבן","yachvâne"],
["pendant que","בזמן ש","bézman ché"],
["poupée","בובה","boubâ"],
["souris","עכבר","akhbâre"],
["sourire","חיוך","khiyoûkh"],
["type","טיפוס","tipoûsse"],
["stupide","טיפש","tipêche"],
["affronter/se mesurer","להתמודד על, עם","léhitmodéde"],
["lutte, rivalité","התמודדות","hitmodédoute"],
["désirer","לחפוץ","lakhpotse"],
["désir","חפיצה","khafitsa"],
["quitter","לעזוב","laazove"],
["départ (abandon)","עזיבה","aziva"],
["départ","יציאה","yêtsi'â"],
["départ (course)","זינוק","zinoûke"],
["sauter","לקפוץ","likpotse"],
["saut","קפיצה","kfitsa"],
["vente","מכירה","mekhira"],
["démolir","להרוס","laharosse"],
["démolition","הריסה","harissa"],
["avant-hier","שלשום","chilchôme"],
["miracle","נס","nesse"],
["miraculeux","נסי","nissî"],
["prince","נסיך","nassikh"],
["princesse","נסיכה","néssikhâ"],
["adolescent","מתבגר","mitbaguêre"],
["adolescence","בגרות","bagroûte"],
["admirer","להתפעל","léhitpaéle"],
["admiration","התפעלות","hitpaaloute"],
["adorer","לסגוד","lisgôde"],
["adoration","סגידה","sguidâ"],
["après-demain","מחרתיים","makharatâyime"],
["inspiration","השראה","hachraah"],
["l'essentiel/principalement","בעיקר","bé'ikar"],
["essentiel","עיקרי","ikarî"],
["espérer","לקוות","lékavote"],
["espoir","תקוה","tikva"],
["essayer","לנסות","lénassote"],
["ethnie","עדה","édâ"],
["origine","מוצא","motsâ"],
["prêt (de fonds)","הלואה","halva'â"],
["prêter","להלוות","léhalvote"],
["passer la nuit (dormir)","ללון","laloune"],
["mordre","לנשוך","linchôkh"],
["gaspiller/dépenser","לבזבז","lévazbéze"],
["gaspillage/perte","בזבוז","bizbouze"],
["valise","מזוודה","mizvadâ"],
["quoi de neuf?","מה איתך","ma itar/itra"],
["sembler","להיראות","léhéra'ôte"],
["semblable (comme)","דומה","domê"],
["il pouvait","היה יכול","aya yakhol"],
["elle pouvait","היתה יכולה","ayéta yékhola"],
["ils pouvaient","היו יכולים","ayou yékholim"],
["elles pouvaient","היו יכולות","ayou yékholote"],
["invitée","אורחת","orakhat"],
["passer; transgresser","לעבור","laavore"],
["faute/contravention","עברה","avera"],
["considérer","לשקול","lichkôle"],
["être considéré","להחשב ל","léhékhachêve lé"],
["considération","שיקול","chikoûle"],
["identifier","לזהות","lézahôte"],
["identique","זהה","zéhê"],
["identification","זיהוי","zihoûye"],
["bâtard","ממזר","mamzêre"],
["gribouiller; papoter","לקשקש","lékachkêche"],
["bavarder, papoter","לפטפט","léfatpête"],
["conscient","הכרתי","hakaratî"],
["connaissance, reconnaissance","הכרה","hakara"],
["connaître, reconnaître","להכיר","léhakire"],
["sang","דם","dame"],
["cerveau","מוח","mô'akh"],
["flot (abondance)","שטף","chêtéfe"],
["hémorragie","שטף דם","chêtéfe dame"],
["infatigable (m.)","בלתי נלאה","biltî nil'ê"],
["infatigable (f.)","בלתי נלאית","biltî nil'êite"],
["stylo","עט","éte"],
["papier","נייר","néyâre"],
["dessiner/noter","לרשום","lirchome"],
["liste","רשימה","rechimâ"],
["porc","חזיר","khazîre"],
["malgré","אף-על-פי","af al pi"],
["présentateur (tv, radio)","שדרן","chadrâne"],
["rôle","תפקיד","tafkîde"],
["titre","כותרת","kotêréte"],
["agir; fonctionner","לפעול","lif'ole"],
["action","פעולה","péoula"],
["consommation de viande","אכילת בשר","akhilat bassar"],
["entre autre","בין השאר","béne hachéare"],
["réduire","לצמצם","létsamtséme"],
["réduction","צמצום","tsimtsoume"],
["souffrance","סבל","sêvéle"],
["pollution","זיהום","zihoûme"],
["causer (provoquer)","לגרום","ligrome"],
["action de causer","גרימה","grima"],
["industrie","תעשייה","ta'assiyâ"],
["un pas","צעד אחד","tsâ'ade ékhad"],
["lire; appeler; nommer","לקרוא","likro"],
["cri; exclamation; appel","קריאה","kriya"],
["parce que","מכיוון","mikévâne"],
["publier","לפרסם","léfarsême"],
["rapidement","במהירות","biméhiroûte"],
["vitesse","מהירות","méhiroûte"],
["aujourd'hui (actuellement)","כיום","kayôme"],
["inventer","להמציא","léhamtsi"],
["invention","המצאה","hamtsaa"],
["rejoindre","להצטרף","léhitstarêfe"],
["recette (cuisine)","מתכון","matkône"],
["végétarien","צמחוני","tsimkhonî"],
["au profit de... (en faveur de)","לטובת","létovâte"],
["complet/entier","שלם","chalême"],
["servir (à table)","להגיש","léhaguîche"],
["plat (mets)","מנה","manâ"],
["environnement","סביבה","svivâ"],
["être envoyé","להשלח","léhichalakh"],
["terroriste","מחבל","mékhabêle"],
["être fermé","להסגר","léhisaguère"],
["coq","תרנגול","tarnégôle"],
["poule","תרנגולת","tarnégôléte"],
["volaille/poulet","עוף","ofe"],
["rat","עכברוש","akhberôche"],
["oiseau","ציפור","tsipôre"],
["fourmi","נמלה","némalâ"],
["cafard","ג'וק","djouke"],
["canard","ברווז","barvâze"],
["bovins","בקר","bakâre"],
["boeuf","שור","chore"],
["moustique","יתוש","yatoûche"],
["mouche","זבוב","zvouve"],
["abeille","דבורה","dvorâ"],
["élever (cultiver)/soigner (s'occuper)","לטפח","létapê'akh"],
["remplir","למלא","lémalé"],
["remplissage","מלוי","milouille"],
["spécialiste","מומחה","moumkhê"],
["demande (économie)","ביקוש","bikoûche"],
["demande","בקשה","bakachâ"],
["approvisionnement/livraison","הספקה","haspaka"],
["cesser/interrompre","להפסיק","léhafsike"],
["cessation/interruption/pause","הפסקה","hafsaka"],
["exagérer","להפריז","léhafrize"],
["exagération","הפרזה","hafraza"],
["défendre","להגן","léhaguene"],
["défense/protection","הגנה","hagana"],
["est-ce que?","האם","ha'ime"],
["humeur/état d'âme","מצב רוח","matsâve roû'akh"],
["cuir au four/faire de la pâtisserie","לאפות","lééfote"],
["cuisson au four","אפיה","afiya"],
["totalement","לגמרי","légamrê"],
["vide","ריק","rike"],
["menteur","שקרן","chakrâne"],
["menteuse","שקרנית","chakrânite"],
["mentir","לשקר","léchakére"],
["mensonge","שקור","chikoure"],
["dessiner/peindre","לציר","létsayere"],
["dessin/peinture","ציור","tsiyure"],
["haïr/détester","לשנוא","lisno"],
["haine/hostilité","שנאה","sin'a"],
["frontière","גבול","gvoule"],
["commun","משותפ","méchoutâfe"],
["disons que ...","נגיד ש","naguide ché"],
["distribuer","לחלק","lékhalêke"],
["distribuer (les rôles)","ללהק","lélahêke"],
["distribution","חלוקה","khaloukâ"],
["distribution (casting)","ליהוק","lihoûke"],
["tigre","נמר","namêre"],
["tigresse","נמרה","némérâ"],
["terrible (m)","נוראי","nora'î"],
["terrible (f)","נוראית","nora'ît"],
["infrastructure","תשתית","tachtîte"],
["feux d'artifice","זיקוקים","zikoukime"],
["parrallèle","מקביל","makbile"],
["plusieurs choses à la fois","כמה דברים במקביל","kama dvarim bémakbile"],
["formulaire","טופס","tôfésse"],
["le jeton est descendu","האסימון ירד","aasimône yarade"],
["lourd","כבד","kavêde"],
["ver à soie","תולעת משי","tolâ'ate mêchi"],
["araignée","עכביש","akavîche"],
["nous tous","כולנו","koulanou"],
["fil","חוט","khoute"],
["fer","ברזל","barzêle"],
["sérieusement (avec sérieux)","ברצינות","birétsinoûte"],
["extérieur","חיצוני","khitsonî"],
["nuage","ענן","anâne"],
["géant","ענק","anâke"],
["arriver (se produire)","לקרות","likrôte"],
["endommager/faire du mal","לפגוע","lifgô'a"],
["confortable/commode","נוח","nô'akh"],
["supplice","עינוי","inoûye"],
["aucun","שום","choume"],
["rien","כלום","kloume"],
["ivre (m)","שתוי","chatoûye"],
["ivre (f)","שתויה","chatoûya"],
["finition","גימור","guimoûre"],
["couloir","מסדרון","misdérône"],
["cheville (anatomie)","קרסול","karsôle"],
["aller-retour","הלוך-חזור","alokh-khazor"],
["foudre","ברק","barâke"],
["ramer","לחתור","lakhtôre"],
["restriction","הגבלה","hagbalâ"],
["produit (de consommation)","מוצר","moutsâre"],
["vomir","להקיא","léhaki"],
["vomissement","הקאה","hakaa"],
["visage","פנים","panîme"],
["volonté","רצון","ratsône"],
["disparaître","להעלם","léhéaléme"],
["disparition","העלמות","héalmoute"],
["renard","שועל","choû'ale"],
["corruption","שחיתות","chkhitoûte"],
["corrompu","מושחת","mouchkhâte"],
["poète","משורר","méchorêre"],
["poétesse","משוררת","méchorêréte"],
["stop (faire du stop)","טרמפ","trêmp"],
["disparu","נעדר","né'édâre"],
["valeur","ערך","êrékh"],
["en particulier","בפרט","bifrâte"],
["résultat","תוצאה","totsa'â"],
["vaincre; diriger (un orchestre)","לנצח את","lénatséakh"],
["victoire; direction (d'orchestre)","נצוח","nitsouakh"],
["de toutes façons","בכל אפן","békol oféne"],
["déplacer (bouger)","להזיז","léhazîze"]];
                
                                
                                                                                                                					
                                var nbNewWordsAdded = 0;
				for (var i = 0, c = default_words.length; i < c; i++) {    
					var w = default_words[i];                       
                                        var rank = i+1;
         
					var wordObj = new Word(w[1],w[0],w[2],-1,-1,rank,false);
					var newWordAdded = window.myEngine._lexicon.addWord(wordObj);
                                        if (newWordAdded)
                                        {                                            
                                            nbNewWordsAdded++;
                                        }
				}
                                if (nbNewWordsAdded > 0)
                                {
                                    window.myEngine._localStorageEngine.saveLexicon(window.myEngine._lexicon, function(){                    
                                        console.log(nbNewWordsAdded + ' new words added, Lexicon saved');
                                    });
                                }
                                
                                fctDone1();
                                
            });            
            
            
            
            
            
            window.myEngine._all_hebrew_words_lexicon = new Lexicon(window.myEngine._localStorageEngine._all_hebrew_words_lexicon_id);                
            for (var i = 0, c = _all_hebrew_words.length; i < c; i++) {    
                var w = _all_hebrew_words[i];     
                var rank = i+1;
         
		var wordObj = new Word(w[0],w[1],w[2],-1,-1,rank,true);
		window.myEngine._all_hebrew_words_lexicon.addWord(wordObj);
            }
            fctDone2();
            /*window.myEngine._localStorageEngine.getLexiconById(window.myEngine._localStorageEngine._all_hebrew_words_lexicon_id, function(lexicon) {                
                var new_lexicon = new Lexicon(window.myEngine._localStorageEngine._all_hebrew_words_lexicon_id);                
                new_lexicon.initFromLexicon(lexicon);
                window.myEngine._all_hebrew_words_lexicon = new_lexicon;
             
                                
                                   var nbNewWordsAdded = 0;
				for (var i = 0, c = _all_hebrew_words.length; i < c; i++) {    
					var w = _all_hebrew_words[i];     
                                        var rank = i+1;
         
					var wordObj = new Word(w[0],w[1],w[2],-1,-1,rank);
					var newWordAdded = window.myEngine._all_hebrew_words_lexicon.addWord(wordObj);
                                        if (newWordAdded)
                                        {
                                            nbNewWordsAdded++;
                                        }
				}
                                if (nbNewWordsAdded > 0)
                                {
                                    window.myEngine._localStorageEngine.saveLexicon(window.myEngine._all_hebrew_words_lexicon, function(){                    
                                        console.log(nbNewWordsAdded + ' new words added, Lexicon saved');
                                        fctDone2();
                                    });           
                                }      
                                else
                                {
                                    fctDone2();
                                }
                                //fctDone2();
            });*/
            
            
            
            
            
            
        };        
};
